//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuncereDataCenter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuncereDataCenterEntities : DbContext
    {
        public SuncereDataCenterEntities()
            : base("name=SuncereDataCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<CityDailyAirQuality> CityDailyAirQuality { get; set; }
        public virtual DbSet<CityHourlyAirQuality> CityHourlyAirQuality { get; set; }
        public virtual DbSet<CityMonthlyAirQuality> CityMonthlyAirQuality { get; set; }
        public virtual DbSet<CityQuarterlyAirQuality> CityQuarterlyAirQuality { get; set; }
        public virtual DbSet<CityYearlyAirQuality> CityYearlyAirQuality { get; set; }
        public virtual DbSet<SuncerePermission> SuncerePermission { get; set; }
        public virtual DbSet<SuncereRole> SuncereRole { get; set; }
        public virtual DbSet<SuncereUser> SuncereUser { get; set; }
        public virtual DbSet<SyncDataQueue> SyncDataQueue { get; set; }
    }
}
