//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuncereDataCenter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuncereDataCenterEntities : DbContext
    {
        public SuncereDataCenterEntities()
            : base("name=SuncereDataCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnualAirQuality> AnnualAirQuality { get; set; }
        public virtual DbSet<MonthlyAirQuality> MonthlyAirQuality { get; set; }
        public virtual DbSet<QuarterlyAirQuality> QuarterlyAirQuality { get; set; }
    }
}
